// Generated by tauri-specta from the Rust commands. Do not edit.
// Regenerate with `cargo xtask gen-bindings`; CI fails on drift.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Facts about the running app: version, OS, directories. The M0 round-trip command. */
	appInfo: () => typedError<AppInfo, ErrorDto>(__TAURI_INVOKE("app_info")),
	getSettings: () => typedError<Settings, ErrorDto>(__TAURI_INVOKE("get_settings")),
	/**
	 *  Replaces the given sections, persists them and returns the whole document. A change to the
	 *  global custom instructions reaches every open chat as a `SystemNote` (10 §4).
	 */
	updateSettings: (patch: SettingsPatch) => typedError<Settings, ErrorDto>(__TAURI_INVOKE("update_settings", { patch })),
	getSecretStoreStatus: () => typedError<SecretStoreStatus, ErrorDto>(__TAURI_INVOKE("get_secret_store_status")),
	getDataInfo: () => typedError<DataInfo, ErrorDto>(__TAURI_INVOKE("get_data_info")),
	/**  Opens the data directory in the system file manager. */
	openDataDir: () => typedError<null, ErrorDto>(__TAURI_INVOKE("open_data_dir")),
	/**  A consistent copy of the database without credentials (06 §5, 11 §2). */
	backupDatabase: (path: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("backup_database", { path })),
	/**  `PRAGMA integrity_check` then `VACUUM`; never automatic (06 §6). */
	maintainDatabase: () => typedError<null, ErrorDto>(__TAURI_INVOKE("maintain_database")),
	listProviders: () => typedError<ProviderRow[], ErrorDto>(__TAURI_INVOKE("list_providers")),
	/**  Stores the key encrypted and forgets the plaintext. Write-only: nothing returns it. */
	setProviderKey: (providerId: ProviderId, key: string) => typedError<KeyStatus, ErrorDto>(__TAURI_INVOKE("set_provider_key", { providerId, key })),
	clearProviderKey: (providerId: ProviderId) => typedError<KeyStatus, ErrorDto>(__TAURI_INVOKE("clear_provider_key", { providerId })),
	/**  Checks the key with the provider's cheapest call and reports the error class on failure. */
	testProvider: (providerId: ProviderId) => typedError<ProviderTest, ErrorDto>(__TAURI_INVOKE("test_provider", { providerId })),
	/**
	 *  The provider's model list from the cache, or fresh when `refresh` is set or the cache is
	 *  stale (docs/plan/02 §2).
	 */
	listModels: (providerId: ProviderId, refresh: boolean) => typedError<ModelInfo[], ErrorDto>(__TAURI_INVOKE("list_models", { providerId, refresh })),
	updateProvider: (providerId: ProviderId, update: ProviderUpdate) => typedError<null, ErrorDto>(__TAURI_INVOKE("update_provider", { providerId, update })),
	createChat: (model: {
	provider: ProviderId,
	model: string,
} | null) => typedError<ChatSummary, ErrorDto>(__TAURI_INVOKE("create_chat", { model })),
	listChats: () => typedError<ChatSummary[], ErrorDto>(__TAURI_INVOKE("list_chats")),
	getChat: (chatId: ChatId) => typedError<ChatDetail, ErrorDto>(__TAURI_INVOKE("get_chat", { chatId })),
	updateChat: (chatId: ChatId, update: ChatUpdate) => typedError<ChatSummary, ErrorDto>(__TAURI_INVOKE("update_chat", { chatId, update })),
	deleteChat: (chatId: ChatId) => typedError<null, ErrorDto>(__TAURI_INVOKE("delete_chat", { chatId })),
	/**  The user's verdict on a reply; `None` clears it. */
	rateTurn: (chatId: ChatId, turnId: TurnId, feedback: "good" | "bad" | null) => typedError<null, ErrorDto>(__TAURI_INVOKE("rate_turn", { chatId, turnId, feedback })),
	/**  Chats by title and messages by text (15 A15). */
	search: (query: string, limit: number) => typedError<SearchHit[], ErrorDto>(__TAURI_INVOKE("search", { query, limit })),
	/**  The assembled system prompt of a chat, read-only (11 §2, Advanced → developer mode). */
	getSystemPrompt: (chatId: ChatId) => typedError<SystemPromptView, ErrorDto>(__TAURI_INVOKE("get_system_prompt", { chatId })),
	/**  Writes the chat to `path` as Markdown or JSON (11 §2, Data & privacy). */
	exportChat: (chatId: ChatId, format: ExportFormat, path: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("export_chat", { chatId, format, path })),
	/**
	 *  Starts a turn and returns at once; the channel carries the turn's events until it ends.
	 *  Attachments are read and stored before anything is sent; a bad one fails the whole call.
	 */
	sendMessage: (chatId: ChatId, text: string, attachments: AttachmentInput[], onEvent: Channel<AgentEventBatch>) => typedError<TurnId, ErrorDto>(__TAURI_INVOKE("send_message", { chatId, text, attachments, onEvent })),
	/**  Drops the chat's last turn and sends its user message again over a fresh channel. */
	retryTurn: (chatId: ChatId, turnId: TurnId, onEvent: Channel<AgentEventBatch>) => typedError<TurnId, ErrorDto>(__TAURI_INVOKE("retry_turn", { chatId, turnId, onEvent })),
	/**  Whether the turn was running. */
	cancelTurn: (turnId: TurnId) => typedError<boolean, ErrorDto>(__TAURI_INVOKE("cancel_turn", { turnId })),
	/**  Reattaches to a running turn: one snapshot, then live batches (05 §3). */
	subscribeTurn: (turnId: TurnId, sinceSeq: number, onEvent: Channel<AgentEventBatch>) => typedError<null, ErrorDto>(__TAURI_INVOKE("subscribe_turn", { turnId, sinceSeq, onEvent })),
	listActiveTurns: () => typedError<ActiveTurn[], ErrorDto>(__TAURI_INVOKE("list_active_turns")),
	/**
	 *  Interactions waiting for the user, oldest first, for one chat or every chat. Cards render
	 *  from the run store while a turn streams; this fills a chat view that mounts later.
	 */
	listPendingInteractions: (chatId: string | null) => typedError<Interaction[], ErrorDto>(__TAURI_INVOKE("list_pending_interactions", { chatId })),
	/**  Answers a pending decision; the waiting turn continues. */
	resolveInteraction: (interactionId: InteractionId, resolution: InteractionResolution) => typedError<Interaction, ErrorDto>(__TAURI_INVOKE("resolve_interaction", { interactionId, resolution })),
	/**  One tool call with its full result, for the detail pane of a finished turn. */
	getToolCall: (callId: CallId) => typedError<ToolCallDto, ErrorDto>(__TAURI_INVOKE("get_tool_call", { callId })),
};

/** Events */
export const events = {
	chatsChanged: makeEvent<ChatsChanged>("chats-changed"),
	interactionsChanged: makeEvent<InteractionsChanged>("interactions-changed"),
	providersChanged: makeEvent<ProvidersChanged>("providers-changed"),
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
};

/* Types */
export type ActiveTurn = {
	chat_id: ChatId,
	turn_id: TurnId,
};

export type AdvancedSettings = {
	/**  Upper bound on one assistant message, in tokens. */
	max_output_tokens?: number,
	/**  Show the assembled system prompt and log raw provider requests (never the key). */
	developer_mode?: boolean,
	/**  How many tool rounds one reply may take before Gantry stops it (01 §3 step 6). */
	max_tool_rounds?: number,
};

export type AgentEvent = {
	/**  Monotonic within the turn, starting at 1. */
	seq: number,
	/**  Milliseconds since the Unix epoch. */
	ts: number,
	turn_id: TurnId,
	event: AgentEventKind,
};

/**  The wire unit on the channel. */
export type AgentEventBatch = {
	turn_id: TurnId,
	events: AgentEvent[],
};

export type AgentEventKind = { type: "turn.started"; chat_id: ChatId; mode: Mode; guard: boolean; model: ModelRef } | 
/**  One per model round: the first assistant message and every one after a tool round. */
{ type: "message.started"; message_id: MessageId; role: Role } | { type: "text.delta"; message_id: MessageId; block: number; text: string } | { type: "thinking.delta"; message_id: MessageId; block: number; text: string } | 
/**  A block is complete; its final part is authoritative. */
{ type: "block.done"; message_id: MessageId; block: number; part: ContentPart } | 
/**  The model started a tool call; arguments may follow as deltas. */
{ type: "tool_call.started"; call_id: CallId; message_id: MessageId; 
/**  Namespace prefix: a connector id, or `gantry` for runtime tools. */
connector: string; connector_name: string; tool: string; model_tool_name: string } | { type: "tool_call.args_delta"; call_id: CallId; fragment: string } | 
/**  Arguments are complete and the call is classified. */
{ type: "tool_call.ready"; call_id: CallId; args: unknown; tier: RiskTier; display: ToolDisplay } | 
/**  The turn waits for the user (04 §10). */
{ type: "decision.requested"; interaction: Interaction } | { type: "decision.resolved"; interaction_id: InteractionId; resolution: InteractionResolution; source: DecisionSource } | 
/**  The call was allowed and is running; `source` says who allowed it. */
{ type: "tool_call.executing"; call_id: CallId; source: DecisionSource } | 
/**
 *  The call ended: with a result, an error result, a denial or a cancellation. The result
 *  content is what the model receives (capped at the transcript limit).
 */
{ type: "tool_call.completed"; call_id: CallId; status: ToolCallStatus; is_error: boolean; duration_ms: number; result_preview: string; result: ResultPart[] } | { type: "provider.notice"; kind: string; detail: string } | { type: "message.completed"; message_id: MessageId; stop_reason: StopReason; usage: Usage | null } | { type: "turn.completed"; status: TurnStatus; usage: Usage | null; duration_ms: number; tool_calls: number } | { type: "error"; code: string; message: string; retryable: boolean } | 
/**  The whole current state of an active turn; first on `subscribe_turn`. */
{ type: "turn.snapshot"; snapshot: TurnSnapshot };

/**
 *  Facts about the running application, returned by the `app_info` command.
 * 
 *  The first typed value to cross the IPC boundary; the bindings pipeline is proven on it.
 */
export type AppInfo = {
	/**  Application version from `Cargo.toml`. */
	version: string,
	/**  Operating system family: `macos`, `windows` or `linux`. */
	os: string,
	/**  CPU architecture, e.g. `aarch64` or `x86_64`. */
	arch: string,
	/**  The application data directory (database, blobs, skills, logs). */
	data_dir: string,
	/**  The log directory. */
	log_dir: string,
	/**  Whether this is a debug build. */
	debug: boolean,
};

export type AppearanceSettings = {
	theme?: Theme,
	density?: Density,
};

export type AttachmentInput = 
/**  A file on disk, chosen in the file dialog or dropped on the window. */
{ kind: "path"; path: string } | 
/**  Bytes the webview already holds (a pasted image or file). */
{ kind: "bytes"; name: string; mime: string; data_base64: string };

export type CacheSupport = "none" | "automatic" | "explicit";

/**
 *  One tool call within a turn. Provider-assigned (`call_…`, `toolu_…`) and round-tripped
 *  unchanged; synthesized as `gantry_<ulid>` when a provider sends none (02 §3).
 */
export type CallId = string;

/**  Everything the chat view needs. */
export type ChatDetail = {
	id: ChatId,
	title: string,
	pinned: boolean,
	archived: boolean,
	project_id: ProjectId | null,
	created_at: number,
	last_message_at: number,
	model: ModelRef,
	mode: Mode,
	guard: boolean,
	effort: ReasoningEffort,
	active_turn: TurnId | null,
	turns: TurnDto[],
};

/**  A conversation. Owns its mode, connectors, grants, roots, instructions and artifacts. */
export type ChatId = string;

export type ChatSettings = {
	/**  Mode for chats created outside a project. */
	default_mode?: Mode,
	/**  Whether the judge guards Auto mode by default. */
	default_guard?: boolean,
	/**  The model for new chats; `None` means [`ModelRef::default_model`]. */
	default_model?: ModelRef | null,
	default_effort?: ReasoningEffort,
	/**  Settings → General → Custom instructions (docs/plan/10 §2, layer 4). At most 4000 chars. */
	custom_instructions?: string,
	suggest_connectors?: boolean,
};

/**  A sidebar row. */
export type ChatSummary = {
	id: ChatId,
	title: string,
	pinned: boolean,
	archived: boolean,
	project_id: ProjectId | null,
	created_at: number,
	last_message_at: number,
	/**  The turn currently streaming, if any. */
	active_turn: TurnId | null,
};

/**  Fields the composer and the sidebar change; absent fields stay as they are. */
export type ChatUpdate = {
	model: ModelRef | null,
	mode: Mode | null,
	guard: boolean | null,
	effort: ReasoningEffort | null,
	title: string | null,
	pinned: boolean | null,
	archived: boolean | null,
	/**  Chat-level custom instructions (10 §2, layer 6). */
	instructions: string | null,
};

export type ChatsChanged = {
	chat_ids: ChatId[],
};

/**  One block of a message. */
export type ContentPart = { kind: "text"; text: string } | { kind: "image"; source: MediaSource; mime: string } | { kind: "document"; source: MediaSource; mime: string; name: string } | { kind: "tool_call"; id: CallId; name: string; args: unknown } | { kind: "tool_result"; call_id: CallId; content: ResultPart[]; is_error: boolean } | 
/**  Model reasoning. Opaque: replayed only to the provider that produced it. */
{ kind: "thinking"; text: string; signature: string | null; provider: ProviderKind } | 
/**  Server-tool blocks, citations and other vendor content persisted and replayed verbatim. */
{ kind: "provider_opaque"; provider: ProviderKind; block_kind: string; json: unknown } | 
/**  An instruction change mid-chat (role `System`). */
{ kind: "system_note"; text: string } | 
/**  Connectors attached or detached mid-chat (role `System`). */
{ kind: "tool_set_change"; added: string[]; removed: string[] };

/**  What Settings → Data & privacy shows and what its buttons do. */
export type DataInfo = {
	data_dir: string,
	database_path: string,
	/**  Size of the database file and its WAL, in bytes. */
	database_bytes: number,
	chat_count: number,
};

/**  Who or what allowed or refused a call (04 §11). */
export type DecisionSource = "mode" | "grant" | "user_once" | "user_chat_grant" | "judge" | "guardrail" | "scope" | "plan_mode";

export type Density = "comfortable" | "compact";

/**
 *  What the frontend receives when a command fails. Never carries secrets or paths the
 *  user did not choose. Rendered by the UI as an inline error row.
 */
export type ErrorDto = { kind: "internal"; message: string } | { kind: "invalid_input"; message: string } | { kind: "not_found"; message: string } | { kind: "io"; message: string } | { kind: "provider"; provider_kind: ProviderErrorKind; message: string } | { kind: "secrets"; message: string } | { kind: "store"; message: string };

export type ExportFormat = "markdown" | "json";

/**  The user's verdict on an assistant reply. */
export type Feedback = "good" | "bad";

export type Interaction = {
	id: InteractionId,
	chat_id: ChatId,
	turn_id: TurnId,
	kind: InteractionKind,
	payload: InteractionPayload,
	status: InteractionStatus,
	resolution: InteractionResolution | null,
	created_at: number,
	resolved_at: number | null,
};

/**  A decision the turn waits on: a permission prompt, an access request, a proposal. */
export type InteractionId = string;

export type InteractionKind = "permission" | "access_request" | "connector_suggestion" | "elicitation" | "auth_required" | "skill_proposal" | "memory_proposal";

/**  The kind-specific body of an interaction. */
export type InteractionPayload = { kind: "permission"; request: PermissionRequest };

/**
 *  How an interaction ended. Grants ("allow for this chat") arrive with M7 as another
 *  permission decision.
 */
export type InteractionResolution = { kind: "permission"; decision: PermissionDecision; 
/**  Shown to the model with a denial. */
message: string | null } | 
/**  The turn was cancelled or the app restarted while the card waited. */
{ kind: "cancelled" };

export type InteractionStatus = "pending" | "resolved" | "cancelled" | "expired";

/**  A chat's count of decisions waiting for the user changed (04 §10: sidebar badges). */
export type InteractionsChanged = {
	chat_id: ChatId,
	pending: number,
};

/**  What a key check returns (OpenRouter's `GET /key`; other providers report less). */
export type KeyInfo = {
	label: string | null,
	limit_usd: number | null,
	limit_remaining_usd: number | null,
	usage_usd: number | null,
	is_free_tier: boolean | null,
};

/**  What the UI may know about a key (docs/plan/11 §4). */
export type KeyStatus = {
	present: boolean,
	/**  The last four characters, when present. */
	hint: string | null,
	/**  The last test failed with an authentication error. */
	invalid: boolean,
};

/**  Where the bytes of an image or document live. */
export type MediaSource = 
/**  Inline, base64-encoded. */
{ kind: "base64"; data: string } | 
/**  A content-addressed blob in the store. */
{ kind: "blob"; hash: string };

/**  One message in a transcript. */
export type Message = {
	id: MessageId,
	role: Role,
	parts: ContentPart[],
	/**  The provider that produced an assistant message; `None` for user and system messages. */
	origin: ProviderKind | null,
	/**  Milliseconds since the Unix epoch. */
	created_at: number,
};

/**  One message in a transcript. */
export type MessageId = string;

/**  The permission mode of a chat (docs/plan/04 §3). */
export type Mode = "manual" | "auto_edit" | "plan" | "auto";

export type ModelCapabilities = {
	tools: boolean,
	parallel_tools: boolean,
	streams_tool_args: boolean,
	vision: boolean,
	pdf_input: boolean,
	reasoning: ReasoningSupport,
	server_web_search: boolean,
	structured_output: boolean,
	prompt_caching: CacheSupport,
};

/**  One row of a provider's model list, as the UI and the catalog cache see it. */
export type ModelInfo = {
	id: string,
	display_name: string,
	context_window: number | null,
	max_output: number | null,
	pricing: Pricing | null,
	capabilities: ModelCapabilities,
};

/**  A model on a provider. */
export type ModelRef = {
	provider: ProviderId,
	model: string,
};

export type PermissionDecision = "allow_once" | "deny";

/**  What a permission card shows (04 §7). */
export type PermissionRequest = {
	call_id: CallId,
	connector: string,
	connector_name: string,
	tool: string,
	model_tool_name: string,
	tier: RiskTier,
	args: unknown,
	display: ToolDisplay,
	/**  The assistant's last sentence before the call, as "why". */
	why: string | null,
	/**  The tool's description, shown on hover. */
	description: string,
};

/**  US dollars per million tokens. */
export type Pricing = {
	input_per_mtok: number | null,
	output_per_mtok: number | null,
	cache_read_per_mtok: number | null,
};

/**  A named group of chats with shared instructions, knowledge and defaults. */
export type ProjectId = string;

/**  The class of a provider failure (docs/plan/02 §7), shared by the client layer and the UI. */
export type ProviderErrorKind = 
/**  The key is missing, invalid or disabled. */
"auth" | 
/**  The account has no credit left. */
"insufficient_credits" | "rate_limited" | "overloaded" | "invalid_request" | "context_too_long" | 
/**  The model id is unknown to the provider. */
"not_found" | "network" | 
/**  The stream ended before the message did. */
"stream_interrupted" | 
/**  The model declined to answer. */
"refused" | "unknown";

/**  A provider account id: `anthropic`, `openai`, `google`, `xai`, `openrouter` or `custom:<ulid>`. */
export type ProviderId = string;

/**  Which client implementation produced or must replay a part. */
export type ProviderKind = "anthropic" | "open_ai_responses" | "open_ai_chat" | "gemini";

export type ProviderRow = {
	id: ProviderId,
	/**  The client implementation: `openai_chat`, `anthropic`, `openai_responses`, `gemini`. */
	kind: string,
	label: string,
	base_url: string | null,
	enabled: boolean,
	key: KeyStatus,
	default_model: string | null,
	/**  Whether this build has a client for the provider's kind. */
	available: boolean,
};

export type ProviderTest = {
	ok: boolean,
	info: KeyInfo | null,
	error: ErrorDto | null,
};

export type ProviderUpdate = {
	default_model: string | null,
	base_url: string | null,
};

export type ProvidersChanged = null;

/**  How much the model should think before answering. */
export type ReasoningEffort = "off" | "low" | "medium" | "high" | "max";

export type ReasoningSupport = { kind: "none" } | 
/**  Accepts an effort level. */
{ kind: "effort" } | 
/**  Accepts a token budget. */
{ kind: "budget" };

/**  One piece of a tool result. */
export type ResultPart = { kind: "text"; text: string } | { kind: "json"; json: unknown } | 
/**  Base64-encoded image bytes. */
{ kind: "image"; data: string; mime: string } | 
/**  A large in-memory object parked by a native connector (01 §7). */
{ kind: "resource"; handle: string; summary: string };

/**  What a tool can do to the world (docs/plan/04 §2). */
export type RiskTier = 
/**  Observes; no side effects. */
"read" | 
/**  Mutates local state inside the chat's roots in a way Gantry can revert. */
"write" | 
/**  Mutates state outside the machine or the roots; not revertible by Gantry. */
"write_external" | 
/**  Runs code with unknown blast radius. */
"execute" | 
/**  Irreversible deletion or force operations. */
"destructive" | 
/**  Acts only on Gantry's own state; never prompts, always logged. */
"app";

/**  Who wrote a message. */
export type Role = "user" | "assistant" | "tool" | "system";

/**  One row of the palette's search (docs/plan/06 §3): a chat by title or a message by text. */
export type SearchHit = {
	kind: SearchHitKind,
	chat_id: ChatId,
	chat_title: string,
	message_id: MessageId | null,
	turn_id: TurnId | null,
	/**  The matched title, or the matching stretch of the message with `…` around it. */
	snippet: string,
	ts: number,
};

export type SearchHitKind = "chat" | "message";

/**  Where the master key lives; shown in Settings → Providers. */
export type SecretStoreStatus = 
/**  The operating system's credential store. */
{ kind: "os_store"; backend: string } | 
/**  A file in the data directory, readable by the user only. Linux without Secret Service. */
{ kind: "file_fallback"; path: string };

/**  Every setting, with a default in code. Persisted one section per row (11 §1). */
export type Settings = {
	appearance?: AppearanceSettings,
	chat?: ChatSettings,
	advanced?: AdvancedSettings,
};

export type SettingsChanged = null;

/**  A section-level patch: every present section replaces the stored one. */
export type SettingsPatch = {
	appearance?: AppearanceSettings | null,
	chat?: ChatSettings | null,
	advanced?: AdvancedSettings | null,
};

/**  Why the model stopped. */
export type StopReason = { kind: "end_turn" } | { kind: "tool_use" } | { kind: "max_tokens" } | { kind: "refusal"; category: string | null } | { kind: "content_filter" } | { kind: "pause_turn" } | { kind: "cancelled" } | { kind: "other"; reason: string };

/**  What developer mode shows: the frozen prompt and the notes appended since (10 §4). */
export type SystemPromptView = {
	snapshot: string,
	notes: string[],
};

export type Theme = "system" | "light" | "dark";

/**
 *  A tool call as the activity feed and the detail pane see it: the `tool_calls` row plus the
 *  result kept in the transcript.
 */
export type ToolCallDto = {
	id: CallId,
	chat_id: ChatId,
	turn_id: TurnId,
	/**  The assistant message that requested the call. */
	message_id: MessageId,
	/**  The namespace prefix the model used: a connector id, or `gantry` for runtime tools. */
	connector: string,
	connector_name: string,
	/**  Un-namespaced tool name. */
	tool: string,
	/**  The name the model used, e.g. `gantry__clock`. */
	model_tool_name: string,
	args: unknown,
	tier: RiskTier,
	status: ToolCallStatus,
	decision_source: DecisionSource | null,
	display: ToolDisplay,
	/**  The first part of the result as text, for the row and the projection. */
	result_preview: string | null,
	/**
	 *  The full result when it is known: from the transcript for a finished turn, from the
	 *  completion event while the turn runs.
	 */
	result: ResultPart[] | null,
	is_error: boolean,
	started_at: number | null,
	ended_at: number | null,
	duration_ms: number | null,
};

/**  Where a tool call is in its life (06 §3, `tool_calls.status`). */
export type ToolCallStatus = 
/**  The model asked for it; arguments may still be streaming. */
"proposed" | "awaiting_decision" | "denied" | "running" | "completed" | "failed" | "cancelled";

export type ToolDisplay = {
	kind: ToolDisplayKind,
	/**  A one-line argument summary in the row, e.g. `path=src/app.rs` or `$ npm test`. */
	summary: string,
};

/**  How the activity row renders a call (05 §2, `tool_call.ready.display`). */
export type ToolDisplayKind = "edit" | "command" | "connector" | "read";

/**  One user message and everything the assistant did in reply. */
export type TurnDto = {
	id: TurnId,
	status: TurnStatus,
	model: ModelRef,
	user: Message,
	/**
	 *  The assistant and tool messages of the turn in order: one assistant message per model
	 *  round, a tool message after each round that called tools. Empty while the turn runs;
	 *  the live messages come through the channel.
	 */
	messages: Message[],
	/**  Every tool call of the turn, in the order the model made them. */
	tool_calls: ToolCallDto[],
	/**  Provider and loop notices shown inline (05 §1): a round cap, a dropped block, a retry. */
	notices: string[],
	usage: Usage | null,
	stop_reason: StopReason | null,
	error: string | null,
	feedback: Feedback | null,
	started_at: number,
	ended_at: number | null,
};

/**  One unit of agent work: a user message and everything until the assistant stops. */
export type TurnId = string;

/**
 *  What a late subscriber needs to draw an in-flight turn: every message of the turn so far
 *  (the last one may still be streaming), the tool calls and the pending decisions.
 */
export type TurnSnapshot = {
	chat_id: ChatId,
	status: TurnStatus,
	/**  Assistant and tool messages of the turn in order; parts in block order. */
	messages: Message[],
	tool_calls: ToolCallDto[],
	pending: Interaction[],
	usage: Usage | null,
	started_at: number,
	/**  The last `seq` this snapshot covers; live events continue from `seq + 1`. */
	seq: number,
};

export type TurnStatus = "running" | "completed" | "cancelled" | "failed" | 
/**  The app was closed while the turn ran (found at the next start). */
"interrupted";

/**  Token accounting for one request, in the provider's own count. */
export type Usage = {
	input: number,
	output: number,
	cache_read: number,
	cache_write: number,
	reasoning: number,
	/**  What the provider says the request cost, in US dollars, when it says so (OpenRouter does). */
	cost_usd: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

