/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactWindowRouteImport } from './routes/artifact-window'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as IncognitoRouteImport } from './routes/incognito'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'
import { Route as CodeIndexRouteImport } from './routes/code.index'
import { Route as CodeSessionIdRouteImport } from './routes/code.$sessionId'
import { Route as DevGalleryRouteImport } from './routes/dev.gallery'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects_.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactWindowRoute = ArtifactWindowRouteImport.update({
  id: '/artifact-window',
  path: '/artifact-window',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IncognitoRoute = IncognitoRouteImport.update({
  id: '/incognito',
  path: '/incognito',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeIndexRoute = CodeIndexRouteImport.update({
  id: '/code/',
  path: '/code/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeSessionIdRoute = CodeSessionIdRouteImport.update({
  id: '/code/$sessionId',
  path: '/code/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevGalleryRoute = DevGalleryRouteImport.update({
  id: '/dev/gallery',
  path: '/dev/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects_/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifact-window': typeof ArtifactWindowRoute
  '/artifacts': typeof ArtifactsRoute
  '/incognito': typeof IncognitoRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/code/$sessionId': typeof CodeSessionIdRoute
  '/dev/gallery': typeof DevGalleryRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/chat/': typeof ChatIndexRoute
  '/code/': typeof CodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifact-window': typeof ArtifactWindowRoute
  '/artifacts': typeof ArtifactsRoute
  '/incognito': typeof IncognitoRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/code/$sessionId': typeof CodeSessionIdRoute
  '/dev/gallery': typeof DevGalleryRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/chat': typeof ChatIndexRoute
  '/code': typeof CodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifact-window': typeof ArtifactWindowRoute
  '/artifacts': typeof ArtifactsRoute
  '/incognito': typeof IncognitoRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/code/$sessionId': typeof CodeSessionIdRoute
  '/dev/gallery': typeof DevGalleryRoute
  '/projects_/$projectId': typeof ProjectsProjectIdRoute
  '/chat/': typeof ChatIndexRoute
  '/code/': typeof CodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifact-window'
    | '/artifacts'
    | '/incognito'
    | '/onboarding'
    | '/projects'
    | '/chat/$chatId'
    | '/code/$sessionId'
    | '/dev/gallery'
    | '/projects/$projectId'
    | '/chat/'
    | '/code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifact-window'
    | '/artifacts'
    | '/incognito'
    | '/onboarding'
    | '/projects'
    | '/chat/$chatId'
    | '/code/$sessionId'
    | '/dev/gallery'
    | '/projects/$projectId'
    | '/chat'
    | '/code'
  id:
    | '__root__'
    | '/'
    | '/artifact-window'
    | '/artifacts'
    | '/incognito'
    | '/onboarding'
    | '/projects'
    | '/chat/$chatId'
    | '/code/$sessionId'
    | '/dev/gallery'
    | '/projects_/$projectId'
    | '/chat/'
    | '/code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactWindowRoute: typeof ArtifactWindowRoute
  ArtifactsRoute: typeof ArtifactsRoute
  IncognitoRoute: typeof IncognitoRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
  CodeSessionIdRoute: typeof CodeSessionIdRoute
  DevGalleryRoute: typeof DevGalleryRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  CodeIndexRoute: typeof CodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifact-window': {
      id: '/artifact-window'
      path: '/artifact-window'
      fullPath: '/artifact-window'
      preLoaderRoute: typeof ArtifactWindowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incognito': {
      id: '/incognito'
      path: '/incognito'
      fullPath: '/incognito'
      preLoaderRoute: typeof IncognitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/': {
      id: '/code/'
      path: '/code'
      fullPath: '/code/'
      preLoaderRoute: typeof CodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/$sessionId': {
      id: '/code/$sessionId'
      path: '/code/$sessionId'
      fullPath: '/code/$sessionId'
      preLoaderRoute: typeof CodeSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/gallery': {
      id: '/dev/gallery'
      path: '/dev/gallery'
      fullPath: '/dev/gallery'
      preLoaderRoute: typeof DevGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId': {
      id: '/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactWindowRoute: ArtifactWindowRoute,
  ArtifactsRoute: ArtifactsRoute,
  IncognitoRoute: IncognitoRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRoute,
  ChatChatIdRoute: ChatChatIdRoute,
  CodeSessionIdRoute: CodeSessionIdRoute,
  DevGalleryRoute: DevGalleryRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  CodeIndexRoute: CodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
