/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactWindowRouteImport } from './routes/artifact-window'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'
import { Route as DevGalleryRouteImport } from './routes/dev.gallery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactWindowRoute = ArtifactWindowRouteImport.update({
  id: '/artifact-window',
  path: '/artifact-window',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevGalleryRoute = DevGalleryRouteImport.update({
  id: '/dev/gallery',
  path: '/dev/gallery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifact-window': typeof ArtifactWindowRoute
  '/artifacts': typeof ArtifactsRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/dev/gallery': typeof DevGalleryRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifact-window': typeof ArtifactWindowRoute
  '/artifacts': typeof ArtifactsRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/dev/gallery': typeof DevGalleryRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifact-window': typeof ArtifactWindowRoute
  '/artifacts': typeof ArtifactsRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/dev/gallery': typeof DevGalleryRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifact-window'
    | '/artifacts'
    | '/onboarding'
    | '/projects'
    | '/chat/$chatId'
    | '/dev/gallery'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifact-window'
    | '/artifacts'
    | '/onboarding'
    | '/projects'
    | '/chat/$chatId'
    | '/dev/gallery'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/artifact-window'
    | '/artifacts'
    | '/onboarding'
    | '/projects'
    | '/chat/$chatId'
    | '/dev/gallery'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactWindowRoute: typeof ArtifactWindowRoute
  ArtifactsRoute: typeof ArtifactsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
  DevGalleryRoute: typeof DevGalleryRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifact-window': {
      id: '/artifact-window'
      path: '/artifact-window'
      fullPath: '/artifact-window'
      preLoaderRoute: typeof ArtifactWindowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/gallery': {
      id: '/dev/gallery'
      path: '/dev/gallery'
      fullPath: '/dev/gallery'
      preLoaderRoute: typeof DevGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactWindowRoute: ArtifactWindowRoute,
  ArtifactsRoute: ArtifactsRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRoute,
  ChatChatIdRoute: ChatChatIdRoute,
  DevGalleryRoute: DevGalleryRoute,
  ChatIndexRoute: ChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
