import {
  CodeIcon,
  FolderIcon,
  GlobeIcon,
  type Icon,
  PlugIcon,
  SparkleIcon,
  TerminalIcon,
} from '@phosphor-icons/react';

import { cn } from '@/lib/utils';
import { MARKS } from '@/lib/marks.generated';

/**
 * A connector's mark: Gantry's own tools as Phosphor glyphs, every catalogued service as the mark
 * you would recognise on its own website, and a two-letter monogram only for something Gantry has
 * never heard of — a server the user added by hand.
 *
 * The marks are generated by `pnpm marks` (`scripts/sync-marks.mjs`): Simple Icons where the
 * vendor is carried there, this repository's own glyph where it is not. Everything is drawn in
 * `currentColor` rather than the brand's colour, because every colour in this app comes from
 * tokens.css (15) — and because a list of sixty logos at full saturation is a fruit salad, not a
 * catalogue.
 */
const GLYPHS: Record<string, Icon> = {
  filesystem: FolderIcon,
  'code-editor': CodeIcon,
  shell: TerminalIcon,
  web: GlobeIcon,
  mcp: PlugIcon,
  /** Runtime tools owned by the agent (03 §9). */
  gantry: SparkleIcon,
};

export function ConnectorMark({
  id,
  name,
  size = 16,
  className,
}: {
  id: string;
  name?: string;
  size?: number;
  className?: string;
}) {
  // A second instance of a connector is namespaced `github-2` (03 §6); it is still GitHub.
  const catalogId = id.replace(/-\d+$/, '');
  const Glyph = GLYPHS[catalogId];
  if (Glyph)
    return <Glyph size={size} className={cn('shrink-0 text-fg-2', className)} aria-hidden />;

  const art = MARKS[catalogId];
  if (art?.kind === 'brand')
    return (
      <svg
        viewBox="0 0 24 24"
        width={size}
        height={size}
        fill="currentColor"
        aria-hidden
        className={cn('shrink-0 text-fg-2', className)}
      >
        <path d={art.d} />
      </svg>
    );
  if (art)
    return (
      <svg
        viewBox="0 0 24 24"
        width={size}
        height={size}
        fill="none"
        stroke="currentColor"
        strokeWidth={1.8}
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden
        className={cn('shrink-0 text-fg-2', className)}
        // Build-time constants from this repository's own icon files, not anything a server sent.
        dangerouslySetInnerHTML={{ __html: art.body }}
      />
    );

  const initials = (name ?? id)
    .split(/[\s-]+/)
    .map((w) => w[0]?.toUpperCase() ?? '')
    .join('')
    .slice(0, 2);
  return (
    <span
      aria-hidden
      style={{ width: size, height: size, fontSize: Math.round(size * 0.45) }}
      className={cn(
        'inline-flex shrink-0 items-center justify-center rounded-1 bg-hover font-medium leading-none text-fg-2',
        className,
      )}
    >
      {initials}
    </span>
  );
}
