import {
  CodeIcon,
  FolderIcon,
  GlobeIcon,
  type Icon,
  PlugIcon,
  SparkleIcon,
  TerminalIcon,
} from '@phosphor-icons/react';

import type { CSSProperties } from 'react';

import { cn } from '@/lib/utils';
import { MARKS } from '@/lib/marks.generated';

/**
 * A connector's mark: Gantry's own tools as Phosphor glyphs, every catalogued service as the mark
 * you would recognise on its own website, and a two-letter monogram only for something Gantry has
 * never heard of — a server the user added by hand.
 *
 * The marks are generated by `pnpm marks` (`scripts/sync-marks.mjs`): Simple Icons where the
 * vendor is carried there, this repository's own glyph where it is not. A brand mark is drawn in
 * the vendor's colour — the one exception to tokens.css holding every colour (15), and one worth
 * making, because a wall of monochrome logos is harder to search than a wall of coloured ones.
 * The generator adjusts each colour per theme so a near-black logo does not disappear into the
 * dark surface; Gantry's own glyphs stay in `currentColor` and follow the text.
 */
const GLYPHS: Record<string, Icon> = {
  filesystem: FolderIcon,
  'code-editor': CodeIcon,
  shell: TerminalIcon,
  web: GlobeIcon,
  mcp: PlugIcon,
  /** Runtime tools owned by the agent (03 §9). */
  gantry: SparkleIcon,
};

export function ConnectorMark({
  id,
  name,
  size = 16,
  className,
}: {
  id: string;
  name?: string;
  size?: number;
  className?: string;
}) {
  // A second instance of a connector is namespaced `github-2` (03 §6); it is still GitHub.
  const catalogId = id.replace(/-\d+$/, '');
  const Glyph = GLYPHS[catalogId];
  if (Glyph)
    return <Glyph size={size} className={cn('shrink-0 text-fg-2', className)} aria-hidden />;

  const art = MARKS[catalogId];
  if (art?.kind === 'brand')
    return (
      <svg
        viewBox="0 0 24 24"
        width={size}
        height={size}
        fill="currentColor"
        aria-hidden
        // `.brand-mark` picks one of the two per theme (styles/globals.css); the values are the
        // vendor's colour already pushed far enough to read on that theme's surface.
        style={{ '--mark-light': art.light, '--mark-dark': art.dark } as CSSProperties}
        className={cn('brand-mark shrink-0', className)}
      >
        <path d={art.d} />
      </svg>
    );
  if (art)
    return (
      <svg
        viewBox="0 0 24 24"
        width={size}
        height={size}
        fill="none"
        stroke="currentColor"
        strokeWidth={1.8}
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden
        className={cn('shrink-0 text-fg-2', className)}
        // Build-time constants from this repository's own icon files, not anything a server sent.
        dangerouslySetInnerHTML={{ __html: art.body }}
      />
    );

  const initials = (name ?? id)
    .split(/[\s-]+/)
    .map((w) => w[0]?.toUpperCase() ?? '')
    .join('')
    .slice(0, 2);
  return (
    <span
      aria-hidden
      style={{ width: size, height: size, fontSize: Math.round(size * 0.45) }}
      className={cn(
        'inline-flex shrink-0 items-center justify-center rounded-1 bg-hover font-medium leading-none text-fg-2',
        className,
      )}
    >
      {initials}
    </span>
  );
}
