/**
 * Writes `src/lib/marks.generated.ts`: one mark per catalogued connector, so the app's lists show
 * the service you recognise rather than two letters of its name.
 *
 * Two sources, in this order:
 *
 * 1. **Simple Icons**, for a service whose mark is published there — the same source the website
 *    uses, so the app and the site show the same shape for the same connector. Only the path is
 *    taken, never the brand colour: every colour in this app comes from tokens.css (15), and
 *    sixty brand hexes would be sixty exceptions to that.
 * 2. **The connector's own `icon.svg`**, for the couple of dozen services Simple Icons does not
 *    carry — Microsoft, Salesforce, Slack and others have asked to be removed from it, and new
 *    services are simply not in it yet. These are Gantry's own glyphs, drawn as one family.
 *
 * Run `pnpm marks` after adding a connector; `tests/marks.test.ts` fails if one has no mark.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import * as simpleIcons from 'simple-icons';

const root = fileURLToPath(new URL('../../..', import.meta.url));
const connectors = join(root, 'desktop/connectors');
const out = join(root, 'desktop/frontend/src/lib/marks.generated.ts');

/** Drawn by Phosphor in the component, because they are Gantry's own tools and not a brand. */
const FIRST_PARTY = new Set(['filesystem', 'code-editor', 'shell', 'web']);

/**
 * Services whose Simple Icons entry is a wordmark — Cal.com's is the words "Cal.com", Xero's is a
 * circle with "xero" written in it — which at the 16px these are drawn at is a smudge. Gantry's
 * own glyph says more.
 */
const WORDMARK = new Set(['cal-com', 'xero']);

/** Where a connector id is not the vendor's Simple Icons slug. */
const ALIAS = {
  'cloudflare-bindings': 'cloudflare',
  'cloudflare-docs': 'cloudflare',
  'cal-com': 'caldotcom',
  'shopify-dev': 'shopify',
  langsmith: 'langchain',
  'incident-io': 'incidentdotio',
};

const key = (slug) => {
  const s = slug.toLowerCase().replace(/[^a-z0-9]/g, '');
  return `si${s.charAt(0).toUpperCase()}${s.slice(1)}`;
};

/** The shapes inside a connector's own icon.svg, without the wrapper. */
const glyphBody = (id) => {
  const svg = readFileSync(join(connectors, id, 'icon.svg'), 'utf8');
  const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
  return body.trim().replace(/\s+/g, ' ');
};

const ids = readdirSync(connectors)
  .filter((d) => {
    try {
      readFileSync(join(connectors, d, 'manifest.json'));
      return true;
    } catch {
      return false;
    }
  })
  .sort();

const lines = [];
let brand = 0;
let glyph = 0;
for (const id of ids) {
  if (FIRST_PARTY.has(id)) continue;
  const icon = WORDMARK.has(id) ? undefined : simpleIcons[key(ALIAS[id] ?? id)];
  if (icon) {
    brand++;
    lines.push(
      `  '${id}': { kind: 'brand', title: ${JSON.stringify(icon.title)}, d: ${JSON.stringify(icon.path)} },`,
    );
  } else {
    glyph++;
    lines.push(`  '${id}': { kind: 'glyph', body: ${JSON.stringify(glyphBody(id))} },`);
  }
}

const header = `// Generated by scripts/sync-marks.mjs — run \`pnpm marks\`. Do not edit by hand.
//
// ${brand} marks from Simple Icons (CC0; the trademarks stay their owners', and a mark here says
// which service a connector reaches, not that anybody endorses Gantry — docs/plan/17 §8), and
// ${glyph} of Gantry's own glyphs for the services Simple Icons does not carry.

/** A brand mark is one filled path; a glyph is this repository's own stroked drawing. */
export type ConnectorMarkArt =
  | { kind: 'brand'; title: string; d: string }
  | { kind: 'glyph'; body: string };

export const MARKS: Record<string, ConnectorMarkArt> = {
`;

writeFileSync(out, `${header}${lines.join('\n')}\n};\n`);
console.log(`wrote ${out}: ${brand} brand marks, ${glyph} glyphs`);
