[package]
name = "gantry-connector-web"
description = "First-party connector: Web."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
gantry-core.workspace = true
gantry-workspace.workspace = true

[dev-dependencies]
serde_json.workspace = true
