// Generated by tauri-specta from the Rust commands. Do not edit.
// Regenerate with `cargo xtask gen-bindings`; CI fails on drift.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Facts about the running app: version, OS, directories. The M0 round-trip command. */
	appInfo: () => typedError<AppInfo, ErrorDto>(__TAURI_INVOKE("app_info")),
};

/* Types */
/**
 *  Facts about the running application, returned by the `app_info` command.
 * 
 *  The first typed value to cross the IPC boundary; the bindings pipeline is proven on it.
 */
export type AppInfo = {
	/**  Application version from `Cargo.toml`. */
	version: string,
	/**  Operating system family: `macos`, `windows` or `linux`. */
	os: string,
	/**  CPU architecture, e.g. `aarch64` or `x86_64`. */
	arch: string,
	/**  The application data directory (database, blobs, skills, logs). */
	data_dir: string,
	/**  The log directory. */
	log_dir: string,
	/**  Whether this is a debug build. */
	debug: boolean,
};

/**
 *  What the frontend receives when a command fails. Never carries secrets or paths the
 *  user did not choose. Rendered by the UI as an inline error row.
 */
export type ErrorDto = { kind: "internal"; message: string } | { kind: "invalid_input"; message: string } | { kind: "not_found"; message: string } | { kind: "io"; message: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

